# fly.toml app configuration file generated for instant-remote-mcp on 2025-06-11T23:10:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'instant-remote-mcp'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.mcp'

[http_service]
  internal_port = 8000

[deploy]
  strategy = "rolling"

[[http_service.checks]]
  grace_period = "5s"
  interval = "2s"
  method = "GET"
  timeout = "1s"
  path = "/health"

[env]
  PORT = '8000'
  SERVER_TYPE = 'http'
  SERVER_ORIGIN = 'https://mcp.instantdb.com'
  IN_FLY = 'true'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
