#!/usr/bin/env bb

(ns publish-packages
  (:require [clojure.string :as str]
            [babashka.process :as proc]
            [cheshire.core :as json]))

(def PACKAGE_PATHS {:core "./packages/core"
                    :admin "./packages/admin"
                    :react "./packages/react"
                    :react-native "./packages/react-native"
                    :cli "./packages/cli"
                    :platform "./packages/platform"
                    :mcp "./packages/mcp"})

(defn package-json-path [main]
  (str main "/package.json"))

(defn jq-set! [path k v]
  (spit path
        (:out (proc/sh "jq" (str k "=\"" v "\"") path))))

(defn has-dependency? [path dep]
  (get-in (json/parse-string (slurp path) false) ["dependencies" dep]))

(defn set-package-versions!
  "Update all package.jsons with the given version"
  [v]
  (doseq [[k path] PACKAGE_PATHS]
    (println (str  "[" (name k) "]" " set version = " v))
    (jq-set! (package-json-path path) ".version" v)))

(defn version-js-body [v]
  (format
   (str/triml "
// Autogenerated by publish_packages.clj
const version = '%s';

export default version;
")
   v))

(defn set-version-js!
  "Update all src/version.js with the given version"
  [v]
  (doseq [[k path] PACKAGE_PATHS]
    (println (str  "[" (name k) "]" " set version.js = " v))
    (spit (format "%s/src/version.js" path)
          (version-js-body v))))

(defn publish-packages! [tag]
  (println "[publish] pnpm publish-packages")
  (if tag
    (proc/shell "pnpm" "publish-packages" "--" "--tag" tag)
    (proc/shell "pnpm" "publish-packages")))

(defn -main [& args]
  (let [tag (first args)
        version (str/trim (slurp "version.md"))]
    (if tag
      (when (not (str/includes? version tag))
        (println (format "When publishing the `%s` tag, the version must contain the tag (e.g. v0.1.2-%s.0)."
                         tag tag))
        (println (format "You provided %s" version))
        (System/exit 1))
      (when (not (re-find #"^v\d+\.\d+\.\d+$" version))
        (println (format "Version should match format v0.1.2, but you provided %s"
                         version))
        (System/exit 1)))
    (set-package-versions! version)
    (set-version-js! version)
    (publish-packages! tag)
    (set-version-js! (str version "-dev"))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
