services:
  postgres:
    image: ghcr.io/instantdb/postgresql:postgresql-16-pg-hint-plan
    ports:
      - "8890:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: instant
      POSTGRES_DB: instant
    volumes:
      - "backend-db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "instant"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "shared_preload_libraries=pg_hint_plan"
      - "-c"
      - "random_page_cost=1.1"

  www:
    ports:
      - "3000:3000"
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile.www
    environment:
      - INSTANT_BACKEND_URL=http://localhost:8888
      - NEXT_PUBLIC_SELF_HOSTED=true

  server:
    depends_on:
      postgres:
        condition: service_healthy
    # TODO: replace with real image
    build:
      context: ./server
      dockerfile: Dockerfile.self-hosted
    environment:
      SELF_HOSTED: "true"
      DATABASE_URL: "postgresql://instant:pass@postgres:5432/instant?sslmode=disable"
    ports:
      - "8888:8888"
      - "6005:6005"

volumes:
  backend-db:
