CREATE EXTERNAL TABLE IF NOT EXISTS `instant_logs_staging` (
  `timestamp` timestamp,
  `event_time` timestamp,
  `level` string,
  `message` string,
  `logger` string,
  `thread` string,
  `exception_type` string,
  `exception_message` string,
  `exception_stacktrace` string,
  `trace_id` string,
  `span_id` string,
  `name` string,
  `duration_ms` bigint,
  `child_threw_exception` boolean,
  `raw` boolean,
  `container_id` string,
  `container_name` string,
  `container_created_at` timestamp,
  `host` string,
  `image` string,
  `stream` string,
  `source_type` string,
  `instance_id` string,
  `app_id` string,
  `op` string,
  `user_id` string,
  `query_hash` string,
  `winner` string,
  `err_data` string,
  `silenced_exception` string,
  `session_id` string,
  `client_event_id` string,
  `original_trace_id` string,
  `group_key` string,
  `thread_name` string,
  `origin` string,
  `socket_origin` string,
  `socket_ip` string,
  `transport` string,
  `start_at` string,
  `end_at` string,
  `err` string,
  `combined` string,
  `i` string,
  `clojure_error_cause` string,
  `clojure_error_class` string,
  `clojure_error_line` string,
  `clojure_error_phase` string,
  `clojure_error_source` string,
  `clojure_error_symbol` string,
  `instant_util_exception_hint` string,
  `instant_util_exception_message` string,
  `instant_util_exception_trace_id` string,
  `instant_util_exception_type` string,
  `amz_cf_id` string,
  `x_amzn_cf_id` string,
  `x_amzn_trace_id` string,
  `amzn_trace_id` string,
  `body` string,
  `event` string,
  `method` string,
  `request_method` string,
  `request_uri` string,
  `route` string,
  `status` string,
  `port` bigint,
  `lsn` string,
  `previous_lsn` string,
  `slot_name` string,
  `tx_bytes` bigint,
  `pid` string,
  `active_connections` bigint,
  `cluster_id` string,
  `db_host` string,
  `idle_connections` bigint,
  `pending_threads` bigint,
  `query_tag` string,
  `job_ids` string,
  `admin` boolean,
  `already_processed` boolean,
  `already_subscribed` boolean,
  `done` boolean,
  `error` boolean,
  `error_on_error` boolean,
  `escaping` boolean,
  `finished` boolean,
  `handle_locally` boolean,
  `iq_topic` boolean,
  `job_not_grabbed` boolean,
  `rate_limited` boolean,
  `requires_tika` boolean,
  `schema_changes` boolean,
  `skip` boolean,
  `skipped_event` boolean,
  `throwing` boolean,
  `tika_enabled` boolean,
  `use_tx_queue` boolean,
  `warning` boolean,
  `gap_ms` bigint,
  `interval_ms` bigint,
  `isn_waited_ms` bigint,
  `latency_ms` bigint,
  `max_isn_wait_ms` bigint,
  `queue_latency_ms` bigint,
  `span_time_ms` bigint,
  `throttle_ms` bigint,
  `timeout_ms` bigint,
  `total_ms` bigint,
  `tx_latency_ms` bigint,
  `tx_ms` bigint,
  `wait_ms` bigint,
  `bytes_read` bigint,
  `bytes_written` bigint,
  `apps_count` bigint,
  `attrs_count` bigint,
  `cached_count` bigint,
  `changed_datoms_count` bigint,
  `changed_sketch_count` bigint,
  `concurrent_handler_count` bigint,
  `connection_count` bigint,
  `created_count` bigint,
  `deleted_count` bigint,
  `entity_count` bigint,
  `event_count` bigint,
  `in_progress_query_count` bigint,
  `iv_topics_count` bigint,
  `job_count` bigint,
  `join_count` bigint,
  `match_count` bigint,
  `num_invalidated_sockets` bigint,
  `num_sockets` bigint,
  `num_tx_steps` bigint,
  `ref_data_count` bigint,
  `retry_worker_count` bigint,
  `revoked_token_count` bigint,
  `row_count` bigint,
  `sink_count` bigint,
  `sketch_count` bigint,
  `token_count` bigint,
  `total_count` bigint,
  `triple_count` bigint,
  `triples_insert_count` bigint,
  `update_count` bigint,
  `wal_record_count` bigint,
  `worker_count` bigint,
  `batch_size` bigint,
  `buffer_byte_size` bigint,
  `chunks_byte_size` bigint,
  `size` bigint,
  `limit` bigint,
  `max_attempts` bigint,
  `max_isn` bigint,
  `max_loops` bigint,
  `max_lsn` string,
  `offset` bigint,
  `timeout` bigint,
  `tries` bigint
)
PARTITIONED BY (
  `year` int,
  `month` int,
  `day` int,
  `hour` int,
  `minute` int
)
STORED AS PARQUET
LOCATION 's3://eb-logs-597134865416-us-east-1-an/logs/env=Instant-experimental-docker-env/'
TBLPROPERTIES (
  'projection.enabled' = 'true',
  'projection.year.type' = 'integer',
  'projection.year.range' = '2026,2035',
  'projection.month.type' = 'integer',
  'projection.month.range' = '1,12',
  'projection.month.digits' = '2',
  'projection.day.type' = 'integer',
  'projection.day.range' = '1,31',
  'projection.day.digits' = '2',
  'projection.hour.type' = 'integer',
  'projection.hour.range' = '0,23',
  'projection.hour.digits' = '2',
  'projection.minute.type' = 'integer',
  'projection.minute.range' = '0,59',
  'projection.minute.digits' = '2',
  'storage.location.template' = 's3://eb-logs-597134865416-us-east-1-an/logs/env=Instant-experimental-docker-env/year=${year}/month=${month}/day=${day}/hour=${hour}/minute=${minute}/',
  'parquet.compression' = 'SNAPPY',
  'classification' = 'parquet'
);
