"""Manual integration tester for the sync `Instant` client.

Mirrors the shape of `main.py` (the async sandbox) for the subset of the
surface exposed on the sync client

Run via:
    uv run --env-file .env python -m src.main_sync

Uncomment a tester call inside `main()` to exercise that surface against a
real server.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Any

from instantdb import Instant, InstantAPIError, InstantError, id

# Captured fixture — generated by the local server (kid 503090235). Same one
# the async webhook receiver testers use; lets us verify validate
# end-to-end without standing up an actual webhook delivery loop.
_FIXTURE_SIG_HEADER = (
    "t=1778610366,kid=503090235,"
    "v1=b4385e8285de38d22b6d8a6bdd03cc75287e356f1adf48cea257a8e6c056c04e"
    "f99af7d8e162afcaa07d201e97c7865cc91e552bd5def8f9ed4b52efc5843406"
)
_FIXTURE_BODY = (
    b'{"payloadUrl":"http://localhost:8888/webhooks/payload/f717e056-94af-'
    b"4556-9eec-288fb27847a1/4e119bf6-ef64-4e86-bf26-49a18dec54b8/0/328/"
    b'5307A1A0","token":"eyJraWQiOiI1MDMwOTAyMzUiLCJ0eXAiOiJKV1QiLCJhbGci'
    b"OiJFZERTQSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg4ODgiLCJzdWIiOiJmNz"
    b"E3ZTA1Ni05NGFmLTQ1NTYtOWVlYy0yODhmYjI3ODQ3YTEiLCJhcHAtaWQiOiJmNzE3Z"
    b"TA1Ni05NGFmLTQ1NTYtOWVlYy0yODhmYjI3ODQ3YTEiLCJleHAiOjE3Nzg2MTM5NjYs"
    b"ImlzbiI6IjAvMzI4LzUzMDdBMUEwIiwid2ViaG9vay1pZCI6IjRlMTE5YmY2LWVmNjQ"
    b"tNGU4Ni1iZjI2LTQ5YTE4ZGVjNTRiOCJ9.SsI2iZ4rD_sDjUcgqyJ0agGXMgjTRU5PK"
    b'gcEQsE-txp5jTNoVouQU-GneTrKR2GmleETEzFrpf_v4HAnCDYABw"}'
)
_FIXTURE_RECEIVED_AT = 1778610366


# ---------- auth ----------


def test_check_magic_code_round_trip(db: Instant) -> None:
    email = f"sandbox-sync-{id()}@instantdb.test"
    try:
        code = db.auth.generate_magic_code(email)
        user, created = db.auth.check_magic_code(email=email, code=code)
        assert user.get("email") == email, f"email mismatch: {user}"
        assert created is True, "fresh user should have created=True"
        print(f"✓ sync generate + check magic code round-trip ({email})")
    finally:
        db.auth.delete_user(email=email)


def test_create_and_verify_token_round_trip(db: Instant) -> None:
    email = f"sandbox-sync-{id()}@instantdb.test"
    try:
        token = db.auth.create_token(email=email)
        user = db.auth.verify_token(token)
        assert user.get("email") == email, f"email mismatch: {user}"
        print(f"✓ sync create_token + verify_token round-trip ({email})")
    finally:
        db.auth.delete_user(email=email)


# ---------- query + transact ----------


def test_transact_query_delete_cycle(db: Instant) -> None:
    goal_id = id()
    title = f"sandbox-sync-{goal_id[:8]}"
    try:
        tx = db.transact(db.tx.goals[goal_id].update({"title": title}))
        assert "tx-id" in tx, f"missing tx-id: {tx}"

        found = db.query({"goals": {"$": {"where": {"id": goal_id}}}})
        assert len(found["goals"]) == 1, f"expected 1, got {len(found['goals'])}"
        assert found["goals"][0]["title"] == title
        print(f"✓ sync transact → query found goal ({goal_id})")
    finally:
        db.transact(db.tx.goals[goal_id].delete())


def test_link_and_nested_query_via_chained_ops(db: Instant) -> None:
    goal_id = id()
    todo_id = id()
    try:
        db.transact(
            [
                db.tx.goals[goal_id].update({"title": "Linked goal"}),
                db.tx.todos[todo_id].update({"title": "Linked todo"}),
                db.tx.goals[goal_id].link({"todos": todo_id}),
            ]
        )
        result = db.query({"goals": {"$": {"where": {"id": goal_id}}, "todos": {}}})
        goals = result["goals"]
        assert len(goals) == 1 and len(goals[0]["todos"]) == 1, f"link broke: {goals}"
        assert goals[0]["todos"][0]["id"] == todo_id
        print(f"✓ sync link + nested query ({goal_id} → {todo_id})")
    finally:
        db.transact(
            [
                db.tx.goals[goal_id].delete(),
                db.tx.todos[todo_id].delete(),
            ]
        )


# ---------- impersonation + debug ----------


def test_debug_query_returns_check_results(db: Instant) -> None:
    scoped = db.as_user(guest=True)
    result = scoped.debug_query({"goals": {}})
    assert "check-results" in result or "result" in result, f"unexpected shape: {result}"
    print("✓ sync debug_query returned permission-checked result")


# ---------- storage ----------


def test_storage_upload_bytes(db: Instant) -> None:
    path = f"sandbox-sync/{id()}.txt"
    try:
        result = db.storage.upload_file(path, b"hello from sync sandbox", content_type="text/plain")
        assert isinstance(result, dict), f"upload result not a dict: {result}"
        print(f"✓ sync storage.upload_file accepted bytes ({path})")
    finally:
        # Delete via $files transaction. Look up the file by path.
        found = db.query({"$files": {"$": {"where": {"path": path}}}})
        for f in found.get("$files", []):
            db.transact(db.tx["$files"][f["id"]].delete())


def test_storage_upload_path(db: Instant) -> None:
    path = f"sandbox-sync/{id()}.txt"
    with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as tmp:
        tmp.write(b"hello from a path-based sync upload")
        tmp_path = Path(tmp.name)
    try:
        result = db.storage.upload_file(path, tmp_path, content_type="text/plain")
        assert isinstance(result, dict), f"upload result not a dict: {result}"
        print(f"✓ sync storage.upload_file accepted pathlib.Path ({path})")
    finally:
        tmp_path.unlink(missing_ok=True)
        found = db.query({"$files": {"$": {"where": {"path": path}}}})
        for f in found.get("$files", []):
            db.transact(db.tx["$files"][f["id"]].delete())


# ---------- rooms ----------


def test_rooms_get_presence_returns_dict(db: Instant) -> None:
    sessions = db.rooms.get_presence("chat", f"sandbox-sync-{id()}")
    assert isinstance(sessions, dict), f"expected dict, got {type(sessions).__name__}"
    print(f"✓ sync rooms.get_presence returned dict (sessions={len(sessions)})")


# ---------- error path ----------


def test_invalid_app_id_raises_parsed_error(db: Instant) -> None:
    api_uri = os.environ.get("INSTANT_API_URI", "http://localhost:8888")
    with Instant(
        app_id="00000000-0000-0000-0000-000000000000",
        admin_token="bogus",
        api_uri=api_uri,
    ) as bogus:
        try:
            bogus.query({"goals": {}})
        except InstantAPIError as e:
            assert e.status >= 400, f"expected non-2xx, got {e.status}"
            print(f"✓ sync invalid creds raised InstantAPIError(status={e.status})")
            return
    raise AssertionError("expected InstantAPIError on bogus creds")


# ---------- webhooks ----------


def test_webhooks_create_list_delete(db: Instant) -> None:
    created = db.webhooks.manager.create(
        url="https://example.com/instant",
        namespaces=["goals"],
        actions=["create", "update", "delete"],
    )
    webhook_id = created["id"]
    try:
        listing = db.webhooks.manager.list()
        assert any(w["id"] == webhook_id for w in listing), f"created webhook not in list: {listing}"
        print(f"✓ sync webhooks create + list ({webhook_id})")
    finally:
        deleted = db.webhooks.manager.delete(webhook_id)
        assert deleted["id"] == webhook_id, f"deleted id mismatch: {deleted}"
        print(f"✓ sync webhooks delete ({webhook_id})")


def test_webhooks_process_payload_dispatches_to_sync_handler(db: Instant) -> None:
    # Sync clients use plain def handlers (no async). Verifies process_payload
    # routes records correctly to a sync handler without await machinery.
    seen: list[dict[str, Any]] = []

    def on_create(record: dict[str, Any]) -> None:
        seen.append(record)

    payload = {
        "data": [
            {
                "namespace": "goals",
                "id": "g1",
                "action": "create",
                "before": None,
                "after": {"id": "g1", "title": "hi"},
                "idempotencyKey": "k1",
            }
        ],
        "idempotencyKey": "p1",
    }
    db.webhooks.process_payload({"goals": {"create": on_create}}, payload)
    assert seen and seen[0]["id"] == "g1", f"sync handler not invoked: {seen}"
    print("✓ sync webhooks process_payload dispatched to plain def handler")


def test_webhooks_validate_with_fixture(db: Instant) -> None:
    webhook_body = db.webhooks.validate(
        signature_header=_FIXTURE_SIG_HEADER,
        body=_FIXTURE_BODY,
        received_at=_FIXTURE_RECEIVED_AT,
    )
    assert webhook_body["payloadUrl"].startswith("http://localhost:8888/webhooks/payload/")
    assert webhook_body["token"].startswith("eyJraWQiOiI1MDMwOTAyMzUi")
    print("✓ sync webhooks validate accepted the fixture")


def test_webhooks_validate_rejects_tampered(db: Instant) -> None:
    tampered = _FIXTURE_BODY.replace(b"5307A1A0", b"5307A1A1")
    try:
        db.webhooks.validate(
            signature_header=_FIXTURE_SIG_HEADER,
            body=tampered,
            received_at=_FIXTURE_RECEIVED_AT,
        )
    except InstantError as e:
        print(f"✓ sync webhooks validate rejected tampered body: {e}")
        return
    raise AssertionError("expected InstantError on tampered body")


# ---------- entry ----------


def main() -> None:
    api_uri = os.environ.get("INSTANT_API_URI", "http://localhost:8888")

    with Instant(api_uri=api_uri) as db:
        # Uncomment a call to run it.
        #
        # auth:
        # test_check_magic_code_round_trip(db)
        # test_create_and_verify_token_round_trip(db)
        #
        # query + transact:
        # test_transact_query_delete_cycle(db)
        # test_link_and_nested_query_via_chained_ops(db)
        #
        # impersonation + debug:
        # test_debug_query_returns_check_results(db)
        #
        # storage:
        # test_storage_upload_bytes(db)
        # test_storage_upload_path(db)
        #
        # rooms:
        # test_rooms_get_presence_returns_dict(db)
        #
        # error path:
        # test_invalid_app_id_raises_parsed_error(db)
        #
        # webhooks:
        # test_webhooks_create_list_delete(db)
        # test_webhooks_process_payload_dispatches_to_sync_handler(db)
        # test_webhooks_validate_with_fixture(db)
        # test_webhooks_validate_rejects_tampered(db)
        pass


if __name__ == "__main__":
    main()
