# AUTOGENERATED from ../_async/. DO NOT EDIT THIS FILE BY HAND.
# Run `make unasync` from client/packages/python/ to regenerate.
"""Prepare an `upload_file` source for streaming.

`_prepare_upload(file, file_size)` returns a body (`bytes` or chunk
iterator), the `content_length`, and an optional cleanup callback for
files the SDK opened itself. `bytes` / `bytearray` go straight through;
`Path` and binary file-likes stream in 64 KiB chunks. Non-seekable
streams require `file_size=`.
"""

from __future__ import annotations

import os
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import IO, NamedTuple

from instantdb._errors import InstantError
from instantdb._io import _read_chunk_offloaded_sync

FileSource = bytes | bytearray | Path | IO[bytes]
_CHUNK_SIZE = 64 * 1024


class _UploadBody(NamedTuple):
    body: object  # bytes, or an iterator that yields chunk bytes
    content_length: int
    cleanup: Callable[[], None] | None


def _validate_file_size(file_size: int) -> None:
    # `bool` is an int subclass; reject explicitly so `file_size=True` raises.
    if not isinstance(file_size, int) or isinstance(file_size, bool) or file_size < 0:
        raise InstantError(f"file_size must be a non-negative int; got {file_size!r}")


def _check_size_match(provided: int | None, actual: int, source: str) -> None:
    if provided is None:
        return
    _validate_file_size(provided)
    if provided != actual:
        raise InstantError(f"file_size={provided} doesn't match {source}'s length ({actual})")


def _seekable_length(file: IO[bytes]) -> int:
    """Bytes remaining in `file` from its current position. Restores the
    position before returning so streaming starts where the user expected."""
    current = file.tell()
    file.seek(0, 2)  # SEEK_END
    end = file.tell()
    file.seek(current)
    return end - current


def _prepare_upload(file: FileSource, file_size: int | None) -> _UploadBody:
    if isinstance(file, (bytes, bytearray)):
        _check_size_match(file_size, len(file), "the in-memory buffer")
        return _UploadBody(bytes(file), len(file), None)

    if isinstance(file, Path):
        # Open first, fstat the fd: stat-then-open would race a concurrent
        # edit and send the wrong content-length.
        fp = file.open("rb")
        try:
            size = os.fstat(fp.fileno()).st_size
            _check_size_match(file_size, size, str(file))
        except BaseException:
            fp.close()
            raise
        return _UploadBody(_aiter_file(fp), size, fp.close)

    if hasattr(file, "read"):
        is_seekable = getattr(file, "seekable", lambda: False)()
        if is_seekable:
            size = _seekable_length(file)
            _check_size_match(file_size, size, "the stream")
        else:
            if file_size is None:
                raise InstantError(
                    "Non-seekable streams need an explicit file_size=N "
                    "(bytes remaining in the stream)."
                )
            _validate_file_size(file_size)
            size = file_size
        return _UploadBody(_aiter_file(file), size, None)

    raise InstantError(
        f"upload_file accepts bytes, pathlib.Path, or a binary file-like; got {type(file).__name__}"
    )


def _aiter_file(fp: IO[bytes]) -> Iterator[bytes]:
    while True:
        chunk = _read_chunk_offloaded_sync(fp, _CHUNK_SIZE)
        if not chunk:
            return
        if not isinstance(chunk, bytes):
            raise InstantError(f"file-like read() must return bytes, got {type(chunk).__name__}")
        yield chunk
