# AUTOGENERATED from ../_async/. DO NOT EDIT THIS FILE BY HAND.
# Run `make unasync` from client/packages/python/ to regenerate.
"""Admin client surface — query, transact, impersonation, debug helpers."""

from __future__ import annotations

import os
from types import TracebackType
from typing import Any

import httpx

from instantdb._errors import InstantError
from instantdb._sync.auth import Auth
from instantdb._sync.http import _HTTP, DEFAULT_API_URI
from instantdb._sync.rooms import Rooms
from instantdb._sync.storage import Storage
from instantdb._sync.webhooks import Webhooks
from instantdb._transact import _flatten_chunks, _TxBuilder, _TxChunk


class Instant:
    def __init__(
        self,
        *,
        app_id: str | None = None,
        admin_token: str | None = None,
        api_uri: str = DEFAULT_API_URI,
        schema: dict[str, Any] | None = None,
        _impersonation: dict[str, str] | None = None,
        _transport: httpx.BaseTransport | None = None,
        _shared_client: httpx.Client | None = None,
    ) -> None:
        if app_id is None:
            app_id = os.environ.get("INSTANT_APP_ID")
        if not app_id:
            raise InstantError("app_id is required: pass app_id=... or set INSTANT_APP_ID env var")
        if admin_token is None:
            admin_token = os.environ.get("INSTANT_ADMIN_TOKEN")
        if not admin_token:
            raise InstantError(
                "admin_token is required: pass admin_token=... or set INSTANT_ADMIN_TOKEN env var"
            )
        self._app_id = app_id
        self._admin_token = admin_token
        self._api_uri = api_uri
        self._impersonation = _impersonation
        self._schema = schema
        self._http = _HTTP(
            app_id=app_id,
            admin_token=admin_token,
            api_uri=api_uri,
            impersonation=_impersonation,
            transport=_transport,
            shared_client=_shared_client,
        )
        self.tx = _TxBuilder()
        self.auth = Auth(self._http, app_id=app_id)
        self.storage = Storage(self._http, app_id=app_id)
        self.rooms = Rooms(self._http, app_id=app_id)
        self.webhooks = Webhooks(self._http, app_id=app_id, schema=schema)

    def as_user(
        self,
        *,
        email: str | None = None,
        token: str | None = None,
        guest: bool = False,
    ) -> Instant:
        if sum([email is not None, token is not None, guest]) != 1:
            raise InstantError("as_user requires exactly one of: email, token, or guest=True")
        if email is not None:
            headers = {"as-email": email}
        elif token is not None:
            headers = {"as-token": token}
        else:
            headers = {"as-guest": "true"}
        return Instant(
            app_id=self._app_id,
            admin_token=self._admin_token,
            api_uri=self._api_uri,
            schema=self._schema,
            _impersonation=headers,
            _shared_client=self._http._client,
        )

    def query(
        self,
        q: dict[str, Any],
        *,
        rule_params: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if rule_params is not None:
            q = {"$$ruleParams": rule_params, **q}
        result = self._http.post(
            "/admin/query",
            params={"app_id": self._app_id},
            json={"query": q, "inference?": False},
        )
        if self._schema is not None:
            return _validate_query_result(result, self._schema)
        return result

    def transact(self, chunks: _TxChunk | list[_TxChunk]) -> dict[str, Any]:
        return self._http.post(
            "/admin/transact",
            params={"app_id": self._app_id},
            json={
                "steps": _flatten_chunks(chunks),
                "throw-on-missing-attrs?": False,
            },
        )

    def debug_query(
        self,
        q: dict[str, Any],
        *,
        rules: dict[str, Any] | None = None,
        rule_params: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        self._require_impersonation("debug_query")
        if rule_params is not None:
            q = {"$$ruleParams": rule_params, **q}
        body: dict[str, Any] = {"query": q, "inference?": False}
        if rules is not None:
            body["rules-override"] = rules
        return self._http.post(
            "/admin/query_perms_check",
            params={"app_id": self._app_id},
            json=body,
        )

    def debug_transact(
        self,
        chunks: _TxChunk | list[_TxChunk],
        *,
        rules: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        self._require_impersonation("debug_transact")
        body: dict[str, Any] = {"steps": _flatten_chunks(chunks)}
        if rules is not None:
            body["rules-override"] = rules
        return self._http.post(
            "/admin/transact_perms_check",
            params={"app_id": self._app_id},
            json=body,
        )

    def _require_impersonation(self, method_name: str) -> None:
        if not self._impersonation:
            raise InstantError(
                f"{method_name} requires an as_user(...) context "
                "since permission checks are user-scoped"
            )

    def close(self) -> None:
        self._http.close()

    def __enter__(self) -> Instant:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()


def _validate_query_result(result: Any, schema: dict[str, Any]) -> dict[str, Any]:
    """Route each top-level namespace's rows through its Pydantic model.

    Unknown namespaces and non-list payloads pass through untouched.
    """
    entities = schema.get("entities", {})
    out: dict[str, Any] = {}
    for ns, items in result.items():
        model = entities.get(ns)
        if model is None or not isinstance(items, list):
            out[ns] = items
            continue
        out[ns] = [model.model_validate(item) for item in items]
    return out
