# AUTOGENERATED from ../_async/. DO NOT EDIT THIS FILE BY HAND.
# Run `make unasync` from client/packages/python/ to regenerate.
"""HTTP layer. Owns the httpx client and computes headers per-request.

Default headers (`app-id`, `authorization`, version stamps) are NOT baked into
the client's `headers=` arg — instead they're computed per-request so we
can opt out of admin auth for endpoints like `/runtime/auth/verify_refresh_token`
that authenticate via the body.
"""

from __future__ import annotations

from typing import Any

import httpx

from instantdb._http_errors import api_error_from_response
from instantdb._version import __version__

DEFAULT_API_URI = "https://api.instantdb.com"
DEFAULT_TIMEOUT = httpx.Timeout(60.0, connect=10.0)


class _HTTP:
    def __init__(
        self,
        *,
        app_id: str,
        admin_token: str,
        api_uri: str = DEFAULT_API_URI,
        impersonation: dict[str, str] | None = None,
        transport: httpx.BaseTransport | None = None,
        shared_client: httpx.Client | None = None,
    ) -> None:
        self._app_id = app_id
        self._admin_token = admin_token
        self._api_uri = api_uri.rstrip("/")
        self._impersonation = impersonation or {}
        if shared_client is not None:
            self._client = shared_client
            self._owns_client = False
        else:
            self._client = httpx.Client(
                base_url=self._api_uri,
                timeout=DEFAULT_TIMEOUT,
                transport=transport,
            )
            self._owns_client = True

    def _headers(self, *, unauthenticated: bool = False) -> dict[str, str]:
        if unauthenticated:
            return {"content-type": "application/json"}
        h: dict[str, str] = {
            "content-type": "application/json",
            "app-id": self._app_id,
            "authorization": f"Bearer {self._admin_token}",
            "Instant-Admin-Version": __version__,
            "Instant-Core-Version": __version__,
        }
        h.update(self._impersonation)
        return h

    def post(
        self,
        path: str,
        *,
        json: Any = None,
        params: dict[str, Any] | None = None,
        unauthenticated: bool = False,
    ) -> Any:
        return self._request(
            "POST", path, json=json, params=params, unauthenticated=unauthenticated
        )

    def get(self, path: str, *, params: dict[str, Any] | None = None) -> Any:
        return self._request("GET", path, params=params)

    def delete(self, path: str, *, params: dict[str, Any] | None = None) -> Any:
        return self._request("DELETE", path, params=params)

    def put_binary(
        self,
        path: str,
        *,
        content: bytes,
        extra_headers: dict[str, str],
        params: dict[str, Any] | None = None,
    ) -> Any:
        headers = self._headers()
        headers.update(extra_headers)
        response = self._client.request(
            "PUT", path, params=params, content=content, headers=headers
        )
        return self._handle_response(response)

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: Any = None,
        unauthenticated: bool = False,
    ) -> Any:
        response = self._client.request(
            method,
            path,
            params=params,
            json=json,
            headers=self._headers(unauthenticated=unauthenticated),
        )
        return self._handle_response(response)

    @staticmethod
    def _handle_response(response: httpx.Response) -> Any:
        if response.is_success:
            return response.json() if response.content else None
        raise api_error_from_response(response)

    def close(self) -> None:
        if self._owns_client:
            self._client.close()
