# AUTOGENERATED from ../_async/. DO NOT EDIT THIS FILE BY HAND.
# Run `make unasync` from client/packages/python/ to regenerate.
"""Storage uploads.

Streams file-backed inputs (Path, open binary files) chunk by chunk so a
large upload doesn't need to be buffered into memory first. `bytes` /
`bytearray` go straight through.
"""

from __future__ import annotations

from typing import Any

from instantdb._sync._upload_io import FileSource, _prepare_upload
from instantdb._sync.http import _HTTP


class Storage:
    def __init__(self, http: _HTTP, *, app_id: str) -> None:
        self._http = http
        self._app_id = app_id

    def upload_file(
        self,
        path: str,
        file: FileSource,
        *,
        content_type: str = "application/octet-stream",
        content_disposition: str | None = None,
        file_size: int | None = None,
    ) -> dict[str, Any]:
        prepared = _prepare_upload(file, file_size)
        try:
            headers = {
                "path": path,
                "content-type": content_type,
                "content-length": str(prepared.content_length),
            }
            if content_disposition is not None:
                headers["content-disposition"] = content_disposition
            return self._http.put_binary(
                "/admin/storage/upload",
                content=prepared.body,
                extra_headers=headers,
                params={"app_id": self._app_id},
            )
        finally:
            if prepared.cleanup is not None:
                prepared.cleanup()
