# AUTOGENERATED from ../_async/. DO NOT EDIT THIS FILE BY HAND.
# Run `make unasync` from client/packages/python/ to regenerate.
"""Webhooks namespace: manager (subscription CRUD) + receiver primitives."""

from __future__ import annotations

from instantdb._sync.webhooks.manager import WebhooksManager
from instantdb._sync.webhooks.receiver import Webhooks

__all__ = ["Webhooks", "WebhooksManager"]
