# AUTOGENERATED from ../_async/. DO NOT EDIT THIS FILE BY HAND.
# Run `make unasync` from client/packages/python/ to regenerate.
"""Receiver primitives for incoming webhook requests.

Three independent steps users compose into framework integration:
    1. `validate` — verify Ed25519 over the raw body and parse the payload reference
    2. `fetch_payloads` — exchange the payload reference for the full record payload
    3. `process_payload` — dispatch each record to its matching handler

No framework adapter (FastAPI / Flask / Django) is bundled — users wire those
in ~10 lines per framework using these primitives.
"""

from __future__ import annotations

from typing import Any

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from instantdb._http_errors import api_error_from_response
from instantdb._sync.http import _HTTP
from instantdb._sync.webhooks.manager import WebhooksManager
from instantdb._webhooks_crypto import (
    DEFAULT_MAX_AGE_SECONDS,
    WebhookBody,
    coerce_webhook_body,
    key_from_jwks,
    known_key,
    normalize_body,
    parse_signature_header,
    parse_webhook_body,
    validate_timestamp,
    verify_signature,
)


class Webhooks:
    def __init__(
        self,
        http: _HTTP,
        *,
        app_id: str,
    ) -> None:
        self._http = http
        self.manager = WebhooksManager(http, app_id=app_id)

    def validate(
        self,
        *,
        signature_header: str,
        body: bytes | str,
        max_age_seconds: int = DEFAULT_MAX_AGE_SECONDS,
        received_at: int | None = None,
    ) -> WebhookBody:
        """Verify `Instant-Signature` and return the parsed webhook body.

        Raises `InstantError` on a malformed header, stale timestamp, unknown
        key id, signature mismatch, or invalid webhook body. Falls back to the
        API's JWKS endpoint when the key is not already known.
        """
        sig = parse_signature_header(signature_header)
        validate_timestamp(
            timestamp=sig.t,
            max_age_seconds=max_age_seconds,
            received_at=received_at,
        )
        key = known_key(self._http._api_uri, sig.kid)
        if key is None:
            key = self._fetch_jwks_key(sig.kid)
        body_bytes = normalize_body(body)
        verify_signature(signature=sig, key=key, body=body_bytes)
        return parse_webhook_body(body_bytes)

    def _fetch_jwks_key(self, kid: str) -> Ed25519PublicKey:
        response = self._http._client.get(
            "/.well-known/webhooks/jwks.json",
            headers={"accept": "application/json"},
        )
        if not response.is_success:
            raise api_error_from_response(response)
        return key_from_jwks(self._http._api_uri, kid, response.json())

    def fetch_payloads(self, webhook_body: WebhookBody) -> dict[str, Any]:
        """Exchange the signed body for the full payload of records.

        `validate` returns a small object with a `payloadUrl` + JWT `token`.
        This fetches that URL with the token and returns the full payload
        (`{"data": [...], "idempotencyKey": "..."}`).
        """
        parsed = coerce_webhook_body(webhook_body)
        payload_url = parsed["payloadUrl"]
        token = parsed["token"]
        response = self._http._client.get(
            payload_url,
            headers={
                "Authorization": f"Bearer {token}",
                "accept": "application/json",
            },
        )
        if not response.is_success:
            raise api_error_from_response(response)
        return response.json()

    def process_payload(
        self,
        handlers: dict[str, Any],
        payload: dict[str, Any],
    ) -> None:
        """Dispatch each record in the payload to its matching handler.

        Resolution per record (matches JS):
            handlers[namespace][action] →
            handlers[namespace]["$default"] →
            handlers["$default"]

        Records with no matching handler are skipped.

        Sequential await (rather than `asyncio.gather`) is deliberate:
        unasync strips the `await` keyword on the way to the sync flavor,
        and a `gather(...)` without `await` would silently no-op a stray
        async handler under `Instant`. Sequential dispatch makes both
        flavors honest at the cost of concurrency across handlers in a
        single payload. The first handler to raise propagates and stops
        the remaining dispatches.

        Handlers under `AsyncInstant` must be `async def`; under `Instant`
        they're plain `def`. Mixing flavors is unsupported.
        """
        for record in payload.get("data") or []:
            namespace = record.get("namespace")
            action = record.get("action")
            handler = _resolve_handler(handlers, namespace, action)
            if handler is None:
                continue
            handler(record)


def _resolve_handler(
    handlers: dict[str, Any],
    namespace: Any,
    action: Any,
) -> Any:
    ns = handlers.get(namespace) if isinstance(namespace, str) else None
    if isinstance(ns, dict):
        exact = ns.get(action) if isinstance(action, str) else None
        if exact is not None:
            return exact
        ns_default = ns.get("$default")
        if ns_default is not None:
            return ns_default
    return handlers.get("$default")
