drop table instant_user_oauth_access_tokens;
drop table instant_user_oauth_refresh_tokens;
drop table instant_oauth_app_redirects;
drop table instant_oauth_app_codes;
drop table instant_oauth_app_client_secrets;
drop table instant_oauth_app_clients;
drop table instant_oauth_apps;
drop type instant_oauth_app_redirect_status;
